### PR TITLE
Fix Intel Map URL

### PR DESCRIPTION
**Pull request by ekuinox**
Intel Map URL has been changed to [intel.ingress.com](https://intel.ingress.com) from [ingress.com/intel](http://ingress.com/intel).
So I fixed Intel Map URLs.
And I wrote Intel Map URL to `buildsettings.py`.
`@@TARGETHOST@@` will be replaced Intel Map URL when build.

英語に自信がないので日本語を付け加えます。
Intel MapのURLが[ingress.com/intel](http://ingress.com/intel)から[intel.ingress.com](https://intel.ingress.com)に変更されていたので、それに伴って修正をしました。
また、`buildsettings.py`にIntel MapのURLを記述して、ビルド時に`@@TARGETHOST@@`に対して置き換えるようにしました。

### CODE REVIEW

**Comment by modos189** [comment]
> Why do we need both include and match?

The point is in different script managers. Some of them do not support include or match.

**Comment by johnd0e** [comment]
> The point is in different userscripts managers. Some of them do not support include or match.

It took place in the past. But is it actual now?

**Comment by modos189** [comment]
Greasemonkey and Tampermonkey recommend @match as more safer.
What's left? Opera (up to version 12)?

**Comment by johnd0e** [comment]
> @match as more safer.

Yes, and 'safer' means more strict, and thus more error-proof in general.
Though it is not important in our case as we have just 1 (or 2) simple predefined rules.

Anyway, I agree that `match` will be sufficient.

**Comment by MysticJay** [comment]
Not sure waht the "more general" part is, but if there was a way to ignore or override all exiting match/include with what we really need would be great.

**Pull request closed without merging**
