### PR TITLE
Full mission support

### PR DESCRIPTION
**Pull request by Meaglin**
Uses proper requests and data to provide a mission interface just like the normal intel map. There are a few extras:

- Mark finished/visited waypoints.
- Mark finished missions.
- Allow event hooks :).
- Show portal status(level and health)

### CODE REVIEW

**Comment by jonatkins** [comment]
Thanks for this.

I haven't looked closely at it yet, but did make a few formatting/wording tweaks

**Comment by Meaglin** [comment]
Thanks for merging this in very cool that it got into the main repo :). 
If you have any questions / suggestions feel free to contact me :)

**Comment by fkloft** [comment]
@meaglin Good work, kudos for that. Your plugin has a different structure than the other plugins, but I like your style better. I think I'll adopt it for further plugins.

I took the liberty to make a little change here, a small fix there - and ended up rewriting quite a lot. Some things were necessary, others were just because I liked it better that way. In the end, it shows more details than before and even supports syncing checked missions and waypoints between devices.

**Comment by lablua** [comment]
The mission path on current version of plugin is invisible if you use the default Ingress map tiles.

**Comment by Meaglin** [comment]
Very nice changes indeed, looks great :).
Also we might need to look at color pallets for different tilesets?

**Comment by michaeldever** [comment]
@Meaglin Agreed, this is a very nice style, the use of bind makes adds a degree of elegance! Might have to modify my work to adopt this style!

**Comment by Meaglin** [comment]
Thanks :)

**Comment by fkloft** [comment]
@meaglin it's hard to change the style according to the base layer, especially since there are lots of different tile providers available. We have to find a color that is neither blue nor green nor in conflict with existing plugins like _cross-links_ or _draw-tools_... :-/

**Comment by jonatkins** [comment]
An orange colour is probably worth trying - reasonable visibility on most map themes.

**Comment by aurosharman** [comment]
I currently seem to have a problem with this component where once I open a mission window, I can't close it; I just have to reload the Intel Map page to get rid of it.  The first view of a mission has no close X at all, just the OK button at the bottom.  Hitting OK does nothing.  If I click on the first waypoint, it changes to a version that has the window-shade and X buttons at the top-right, and Zoom to Mission and OK at bottom right; but OK and X do nothing.

**Pull request merged**
