### PR TITLE
Added new plugin extend-poly-lines.user.js

### PR DESCRIPTION
**Pull request by TheSned**
Please consider adding my plugin to the core code base. Thanks!

### CODE REVIEW

**Comment by TheSned** [comment]
extend-polygon-lines extend-polyline-lines

**Comment by ryantheleach** [comment]
Thanks for this, I'd been struggling working it out. 

I think I prefer the approach I was trying to take, that instead of extending all poly lines, you were able to draw construction lines / extend specific lines, however I never finished it :S

Sorry for the poor gif, my cursor is actually to the right where the tooltip is.
image


Anyway, by snapping to the portals you can be sure that you are following the right line, then from there it would draw out as far as you drew, a dotted line much like you have. except it would have a beginning and end and not give you a big mess if you zoom out on multiple layers.

**Comment by TheSned** [comment]
I agree that it would be nice to be able to choose which lines are extended and maybe even by how much. However, I use this on mobile with auto draw quite a bit, which doesn't seem like it would work well with your method.

**Comment by ryantheleach** [comment]
Alternately, it's only the outer layers that are needed to be drawn right? 
Or if you do need the layers underneath, they could do better with being a different color, just to more easily distinguish them?

**Comment by TheSned** [comment]
I've thought about maybe an option or "layer" to include just the top layer of drawn items or not. However, I haven't had time to code something like that. It depends on the plan you're working on. Sometimes that's all you'd need, but if you have multiple spines, then just the top layer wouldn't work.

**Comment by ryantheleach** [comment]
@TheSned I see what you mean about auto-draw and mobile. I've only just started using it myself since my Home PC power supply blew.

Maybe toggle the behaviour depending on whether it's on desktop or mobile?

**Comment by TheSned** [comment]
I will not be making any more changes to this plugin. I have lots of other ideas for plugin development and will be focusing any free time I have on those ideas.  If seeing the extra lines is annoying when zooming out, you can just turn off the layer. Feel free to fork my branch, tweak the plugin yourself, and make a separate pull request.

**Pull request closed without merging**
