### PR TITLE
RegionScoreboard improved

### PR DESCRIPTION
**Pull request by McBen**
a) refactored "region_scoreboard.js" 
b) improved "mean line" by using median as default value to predict future values
c) timers for next CP and final CP
..and minor stuff

Example:
unbenannt

/edit: (tooltip is not transparent!)

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
I like it generally (as you might expect as the person who filed the feature request it's at least partly in response to!). A few comments:

1. I think the checkpoint timers are unnecessary, since that's covered by the score-cycle-times plugin.
2. The percentages in the tooltip don't seem useful to me vs. just the raw numbers, I think they clutter it.
3. While I like the "Requires" counts I'm not sure what they mean precisely, especially the checkpoint count breakdown. I guess the 1-cycle/checkpoint one is exactly the current un-averaged score difference, i.e. how much additional MU would be needed to win vs. the median-based projection if the fields only lasted one checkpoint, and the others are then how much extra MU you'd need for that specified number of checkpoints. Assuming that's right, I think I'd say most of the counts aren't that useful, perhaps just the one-checkpoint one (for "how big of a mega field needs to get thrown") and whatever is the current total number of remaining checkpoints (for "how much extra field would we need to maintain to win"). I'd also make sure to be clear that you mean checkpoints and not cycles.

Just for the sake of anyone else looking into this, note that the median is used only for projecting the instantaneous score at checkpoints that haven't yet happened; the line always shows the rolling mean as of a specific checkpoint. The parenthesized value is the projected value with the extrapolation for the 35th checkpoint.

**Comment by mxxcon** [comment]
What are do the numbers in () show? 961723 and 821347
I agree with @ianmcorvidae's points 1 and 2.
Is the hover window supposed to be so "unreadable transparent" or is it just an artifact while screenshot?

**Comment by ianmcorvidae** [comment]
@mxxcon they're the projected value with the extrapolation for the 35th checkpoint -- i.e., the expected values for the end of the cycle (assuming remaining checkpoints' scores are the median of past checkpoint scores).

**Comment by McBen** [comment]
1 => pro & con's ->
the plugin is always visible...even if you don't care; my is tied to the region-score where it belongs to
the plugin get the times by pure calculation; my is getting it by pure server data

2=> it's inside the tooltip..it's just additional information; it's much the same as the colored bars on the main screen; maybe a little bit unnecessary but IMHO not too confusing

3=>first off: yes, it should be 'checkpoints' not 'cycles' ..will be fixed
and yes it's how much MU's a faction need based on the estimated value (=current mean + rest*median)
and yes, in fact only the first value is really needed the rest is just 'fun to know' ... but again it's just a tooltip


@mxxcon the transparency is a screenshot artifact, it is displayed like any other tool tip

**Comment by mxxcon** [comment]
I just tried your changes and its checkpoint times are off by 1 hour early.
Also the graph has scrollbars by a few pixels, I think it might be because our region cell scores are in millions rather than thousands...
clipboard01

**Comment by McBen** [comment]
thx, for testing. 
- Scrollbars is a style issue ('caused be 'high' values) 
- times are calculated by server response: "timeToEndOfBaseCycleMs" ....maybe a 'to-local' time conversion problem?..have to investigate

- a known issue: mobile view

**Comment by mxxcon** [comment]
Any chance to fix these things?

**Comment by McBen** [comment]
It now uses the same algo as the score-cycle-times-plugin (the math way instead of the server data).
Style fixed & Tooltip cleanup.

**Comment by johnd0e** [comment]
@McBen 
Is this patch stable enough to replace current scoreboard code?
(We are interesting to merge it in IITC-CE).

**Comment by McBen** [comment]
AFAIK there are still some css issues with appearing scrollbars depending on browser and system.

**Comment by johnd0e** [comment]
And I see some commits are not in this PR: https://github.com/McBen/ingress-intel-total-conversion/commits/994f9932b6ad5b8f7d11ea3ac902ce953ac046eb/code/dialog_region_scoreboard.js

**Comment by McBen** [comment]
only the last one has a valid change (https://github.com/McBen/ingress-intel-total-conversion/commit/994f9932b6ad5b8f7d11ea3ac902ce953ac046eb#diff-c551b22b81d87ce49ba3799fe43c6e18). 

Rest was only 'caused by code style.
(and my bad behavior to mix code changed in these commits ... lesson learned)

**Comment by McBen** [comment]
closed because stale project

**Pull request closed without merging**
