### PR TITLE
Update player-tracker.user.js

### PR DESCRIPTION
**Pull request by kddmitry**
To be able to see the nicknames of players under their labels

### CODE REVIEW

**Review by pleasantone — CHANGES_REQUESTED** [review]
This is a great idea, but you have committed the expanded user.js, not the pre-built one. You have a bunch of crud in here that should not be committed. Please fix it.

**Review by pleasantone — CHANGES_REQUESTED** [review]
Also consider using the standard team colors, not blue and green, and clean out the dead/commented code.

**Comment by kddmitry** [comment]
I clean out the dead/commented code. what's about last commit ?

**Comment by mxxcon** [comment]
Could you post a screenshot of what it looks like?

**Comment by kddmitry** [comment]
Here:
example 1
example 2
example 3

**Comment by mxxcon** [comment]
Is there an option to turn off this layer? In a busy area I suspect this might be unusable.

**Comment by pleasantone** [comment]
I'm sorry I haven't tested it yet, but with similar types of changes, I have seen problems when the map gets moved or pound or zoomed, or the person in question moves on the map. Are those cases handled correctly in this one?

**Comment by kddmitry** [comment]
@mxxcon 
> Is there an option to turn off this layer? In a busy area I suspect this might be unusable.

Yep, it looks like this :
example 1

@pleasantone 

> I'm sorry I haven't tested it yet, but with similar types of changes, I have seen problems when the map gets moved or pound or zoomed, or the person in question moves on the map. Are those cases handled correctly in this one?

I have not encountered such a problem when the map gets moved or zoomed

**Comment by Dedko** [comment]
ES6 isn't supported by PhantomJS (let declaration)

>  (Unexpected token: name (iColor) (line: 433, col: 8))

It used in many screenshot bots, and other projects.

**Pull request closed without merging**
