### PR TITLE
Bookmark util functions

### PR DESCRIPTION
**Pull request by reckter**
Finished implementing #980:

Created utility functions (and docs) for the bookmarks plugins:
- added folder ability to addPortalBookmark(guid, latlng, label, folder) 
  added methods:
- addMapBookmark(name, lat, lat, zoom, folder)
- addFolder(name, isPortalFolder)
- removePortalByGuid(guid)
- removePortalFromFolder(folder, guid)
- removeFolder(id)
- removeMap(id)

Also used these methods in the addElement and removeElement method, so no duplicate code was crated.

### CODE REVIEW

**Comment by tillmanj** [comment]
Nested folders would go a long way to improving bookmark handling as well

**Comment by reckter** [comment]
Yes you're right, but I guess that might need a major refactor of that plugin. I'm not sure I want to that though cause I'm not sure it will be heated :/ (a simple pull request as #993 has not heared response yet, and I don't want to put time into something that will not have any effect anyway)

**Comment by reckter** [comment]
Updated, so this can be easily merged

**Comment by reckter** [comment]
Closing this for cleanup purposes of my open PRs

**Pull request closed without merging**
